[build]
 publish = "dist"
 command = "npm run build"
 
[context.production.environment]
HUGO_VERSION = "0.49.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "npm run build-preview"
  
[context.deploy-preview.environment]
HUGO_VERSION = "0.49.2"

[context.branch-deploy.environment]
HUGO_VERSION = "0.49.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
[[redirects]]
 from = "http://www.peakstudentcouncil.org/*"
 to = "http://peakstudentcouncil.org/:splat"
 status = 301
 force = true
